import Link from "next/link";

export const metadata = {
  title: "Terms of Service | Picture Pros",
  description: "Terms of Service for Picture Pros AI portrait generation service.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-300">
      <nav className="border-b border-white/5 bg-slate-950/80 backdrop-blur-xl sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 h-16 flex items-center">
          <Link href="/" className="flex items-center">
            <img src="/assets/logo/PP%20LOGO%20AI.png" alt="Picture Pros" className="h-9 sm:h-10" />
          </Link>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12 sm:py-16">
        <h1 className="text-3xl sm:text-4xl font-black text-white mb-2">Terms of Service</h1>
        <p className="text-sm text-slate-500 mb-10">Last updated: February 23, 2026</p>

        <div className="space-y-8 text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-bold text-white mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Picture Pros (&quot;the Service&quot;) at{" "}
              <strong className="text-white">picturepros.ai</strong>, you agree to be bound by these Terms of
              Service. If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">2. Description of Service</h2>
            <p>
              Picture Pros provides AI-powered sports portrait generation. Users upload photos and provide
              player details, and our AI generates stylized sports portraits. The Service offers both free
              and paid tiers through a credit-based system.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">3. Account Registration</h2>
            <p>
              To use certain features, you must create an account using Google sign-in or email authentication.
              You are responsible for maintaining the confidentiality of your account and for all activities
              that occur under your account. You must provide accurate and complete information when creating
              your account.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">4. Credits &amp; Payments</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                New users receive a limited number of free portrait generations.
              </li>
              <li>
                Additional portraits require purchasing credit packs. Prices are displayed at the time of
                purchase.
              </li>
              <li>
                All payments are processed securely through Stripe. By making a purchase, you agree to
                Stripe&apos;s terms of service.
              </li>
              <li>
                <strong className="text-white">Credits are non-refundable</strong> once purchased, except
                where required by applicable law.
              </li>
              <li>
                Each portrait generation consumes one credit, regardless of the output quality or whether
                you choose to download the result.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">5. User Content &amp; Uploaded Photos</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                You retain ownership of the photos you upload. By uploading a photo, you grant us a temporary,
                limited license to process the image for the purpose of generating your portrait.
              </li>
              <li>
                You represent that you have the right to upload and use any photos you submit, including
                appropriate consent from the individuals depicted (or their parents/guardians for minors).
              </li>
              <li>
                You may use the generated portraits for personal, non-commercial purposes. Commercial use
                (e.g., resale, prints for profit) may require additional licensing.
              </li>
              <li>
                You must not upload content that is illegal, harmful, abusive, or violates the rights of others.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">6. AI-Generated Content</h2>
            <p>
              Portraits are generated by artificial intelligence and may not be perfect. We do not guarantee
              specific results, exact likeness, or particular quality levels. AI outputs may vary between
              generations. We are not responsible for any unintended or inaccurate representations in the
              generated images.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">7. Prohibited Uses</h2>
            <p className="mb-3">You agree not to:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>Use the Service for any unlawful purpose.</li>
              <li>Upload photos of individuals without their consent (or parental consent for minors).</li>
              <li>Attempt to reverse-engineer, hack, or interfere with the Service.</li>
              <li>Use the Service to generate misleading, defamatory, or harmful content.</li>
              <li>Resell or redistribute credits or access to the Service.</li>
              <li>Use automated tools or bots to access the Service.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">8. Limitation of Liability</h2>
            <p>
              The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any
              kind, either express or implied. To the fullest extent permitted by law, Picture Pros shall not
              be liable for any indirect, incidental, special, consequential, or punitive damages arising from
              your use of the Service. Our total liability shall not exceed the amount you paid to us in the
              12 months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">9. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your account at any time for violation of these
              terms or for any other reason at our discretion. Upon termination, your right to use the Service
              will immediately cease. Any unused credits may be forfeited upon termination for cause.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">10. Changes to Terms</h2>
            <p>
              We may modify these Terms of Service at any time. We will notify users of material changes by
              updating the &quot;Last updated&quot; date. Continued use of the Service after changes constitutes
              acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">11. Governing Law</h2>
            <p>
              These terms shall be governed by and construed in accordance with the laws of the United States,
              without regard to its conflict of law provisions.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">12. Contact Us</h2>
            <p>
              If you have questions about these Terms of Service, please contact us at:{" "}
              <a href="mailto:faucheauxcoleman@gmail.com" className="text-indigo-400 hover:text-indigo-300 underline">
                faucheauxcoleman@gmail.com
              </a>
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-slate-800 flex flex-wrap gap-4 text-xs text-slate-600">
          <Link href="/" className="hover:text-slate-400 transition">Home</Link>
          <Link href="/privacy" className="hover:text-slate-400 transition">Privacy Policy</Link>
        </div>
      </div>
    </div>
  );
}
